name: med_reminder
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:

  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_svg: ^2.0.5
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  get: ^4.6.5
  intl: ^0.18.1
  provider: ^6.0.5
  time: ^2.1.3
  timezone: ^0.9.2
  url_launcher: ^6.1.12

  # curved_navigation_bar: ^1.0.3 #latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
